version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - "./:/var/www"
      - "./docker/nginx/sites/app.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./docker/php
      args:
        - USER_ID
        - GROUP_ID
    container_name: php-fpm
    volumes:
      - "./:/var/www"
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    expose:
      - "9000"
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegram-bot
      MYSQL_USER: telegram-bot
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "8084:80"
volumes:
  dbdata: